spring:
  application:
    name: pressuremonitor
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/pressure_monitor_development
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 60000