spring:
  application:
    name: pressuremonitor
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/pressure_monitor_test?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  