spring:
  application:
    name: pressuremonitor
  datasource:
    url: ${PRESSURE_MONITOR_DB_URL}
    username: ${PRESSURE_MONITOR_DB_USERNAME}
    password: ${PRESSURE_MONITOR_DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
